

/* Create Tables */

CREATE TABLE BREWERY
(
	BREWERY_ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '蔵元ID',
	BREWERY_NAME VARCHAR(255) NOT NULL COMMENT '蔵元名',
	PRIMARY KEY (BREWERY_ID)
) COMMENT = '蔵元';


CREATE TABLE CUSTOMER
(
	CUSTOMER_ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT COMMENT '顧客ID',
	CUSTOMER_NAME VARCHAR(255) NOT NULL COMMENT '顧客名',
	PRIMARY KEY (CUSTOMER_ID)
) COMMENT = '顧客';



