greeting:
  message: "hello"

quarkus:
  datasource:
    db-kind: mysql
    username: root
    password:
    jdbc:
      url: jdbc:mysql://localhost:3306/emishudb
      min-size: 3
      max-size: 13      
  doma:
    dialect: mysql
    batch-size: 10
    fetch-size: 50
    max-rows: 500
    query-timeout: 5000
    sql-load-script:
    